UPDATE PUBLIC.ADP_CITIES_PRICE_DROP
SET IS_ACTIVE          = FALSE,
    IS_CHANGE_PROMOTED = TRUE,
    USER_ENDED         = '{user_email}',
    DT_FINISHED        = CURRENT_TIMESTAMP
WHERE ID_CITY IN (SELECT DISTINCT PML_DIM_SESSION.ID_CITY
                  FROM PUBLIC.ADP_UPDATES_REGISTRY
                      JOIN DWH_FEVER.PUBLIC.PML_DIM_SESSION
                          USING (ID_SESSION)
                  WHERE ID_RUN = '{id_run}')
    AND IS_ACTIVE = TRUE
;
