WITH CHANNELS_TABLE AS (
    SELECT
        CP.ID                                   AS ID_SESSION,
        TO_JSON(ARRAY_AGG(CSTC.CHANNEL_ID))     AS CHANNEL_IDS
    FROM DWH_FEVER.LAKE.PREMILLER_LAKE_CORE_PLAN CP
        INNER JOIN DWH_FEVER.LAKE.PREMILLER_LAKE_CORE_SESSIONTYPETIERFORCHANNEL CSTC
            ON CP.SESSION_TYPE_ID = CSTC.SESSION_TYPE_ID
    GROUP BY CP.ID
)

SELECT PDS.MAIN_PLAN_ID                             AS ID_PLAN,
       PI.ID_SESSION,
       IFF(
               CMPMS.MUST_USE_TAX_BASE,
               IFF(PLCS.IS_ACTIVE, PLCS.TICKET_PRICE_TAX_BASE, PDS.TICKET_PRICE_TAX_BASE),
               IFF(PLCS.IS_ACTIVE, PLCS.TICKET_PRICE, PDS.TICKET_PRICE)
       )                                            AS CURRENT_PRICE,
       CMPMS.MUST_USE_TAX_BASE,
       CDC.NM_SMALL_UNIT_CONV,
       CURRENT_PRICE * PI.RELATIVE_PRICE_MULTIPLIER AS NEW_PRICE,
       PLCS.CURRENCY,
       CT.CHANNEL_IDS,
       PI.INTERVENTION_LABEL,
       PI.PRICE_CHANGE_INFO
FROM METABASE.PRICE_MULTIPLIER_INTERVENTION PI
    LEFT JOIN DWH_FEVER.LAKE.PREMILLER_LAKE_CORE_SESSIONPRICE PLCS
        ON PI.ID_SESSION = PLCS.SESSION_ID
    INNER JOIN DWH_FEVER.LAKE.PREMILLER_LAKE_CORE_PLAN PDS
        ON PDS.ID = PI.ID_SESSION
    INNER JOIN DWH_FEVER.PUBLIC.COM_DIM_CURRENCY CDC
        ON CDC.CD_CURRENCY = PLCS.CURRENCY
    INNER JOIN DWH_FEVER.LAKE.PREMILLER_LAKE_CORE_MAINPLAN PDP
        ON PDS.MAIN_PLAN_ID = PDP.ID
    INNER JOIN DWH_FEVER.LAKE.PREMILLER_LAKE_CORE_MAINPLANMANAGEMENTSETTINGS CMPMS
        ON CMPMS.MAIN_PLAN_ID = PDP.ID
    LEFT JOIN CHANNELS_TABLE CT
        ON CT.ID_SESSION = PI.ID_SESSION
WHERE PDS.STARTS_AT > CURRENT_TIMESTAMP() -- dont change finished sessions
  AND PI.INTERVENTION_LABEL = '{price_intervention_label}'
  AND PLCS.CHANNEL_ID = 'fever-marketplace';
